name: ci

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '.terraform.lock.hcl'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '.terraform.lock.hcl'
      - '.github/workflows/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  TERRAFORM_VERSION: 1.15.2

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: terraform fmt
        run: terraform fmt -check -recursive

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: terraform init
        run: terraform init -input=false

      - name: terraform validate
        run: terraform validate
